on:
  push:
    branches:
    - master

  deployment:
    - name: GitHub Action for DigitalOcean - doctl
      uses: digitalocean/action-doctl@v2.2.0
      with:
           token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

